name: Pull WordPress Content

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'The URL to download the ZIP file from'
        required: true
        default: 'https://example.com/wp-content.zip'
      file_name:
        description: 'The name of the ZIP file'
        required: true
        default: 'wp-content.zip'

jobs:
  sync_wp_to_repo:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current state of the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download the ZIP file from the provided URL
      - name: Download ZIP file
        run: |
          curl -O ${{ github.event.inputs.file_url }}

      # Step 3: Extract the downloaded ZIP file
      - name: Extract ZIP file
        run: |
          7z x ${{ github.event.inputs.file_name }} -y

      # Step 4: Remove the ZIP file after extraction
      - name: Remove ZIP file
        run: |
          rm -f ${{ github.event.inputs.file_name }}

      # Step 5: Remove files that are not present in the ZIP (excluding .github, .gitignore, .gitattributes)
      - name: Clean up repository
        run: |
          # List the existing files that should NOT be deleted (like .github)
          EXCLUDE="--exclude=.github --exclude=.gitignore --exclude=.gitattributes"

          # Find all files in the repo (ignoring the excluded ones)
          for file in $(find . -type f $EXCLUDE); do
            if [[ ! -e $file ]]; then
              echo "Deleting $file as it does not exist in the ZIP"
              rm -f $file
            fi
          done

          # Find all directories in the repo (ignoring the excluded ones)
          for dir in $(find . -type d $EXCLUDE); do
            if [[ ! -d $dir ]]; then
              echo "Deleting $dir as it does not exist in the ZIP"
              rm -rf $dir
            fi
          done

      # Step 6: Commit and push the changes
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git config --global user.name "GitHub Action"
            git config --global user.email "action@github.com"
            git commit -m "Update from WordPress ${GITHUB_EVENT_INPUTS_FILE_NAME} [skip ci]"
            git push
          fi
